auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  instance_addr: 127.0.0.1
  path_prefix: /tmp/loki
  storage:
    filesystem:
      chunks_directory: /tmp/loki/chunks
      rules_directory: /tmp/loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2024-04-01
      store: tsdb # Change index type to tsdb
      object_store: filesystem
      schema: v13 # Upgrade schema to v13
      index:
        prefix: index_
        period: 24h

limits_config:
  ingestion_rate_mb: 1024
  ingestion_burst_size_mb: 1024
  allow_structured_metadata: true # Structured metadata allowed with v13 and tsdb

ruler:
  alertmanager_url: http://localhost:9093
# Uncomment to disable usage statistics reporting
analytics:
  reporting_enabled: false
