version: "3.4"
services:
  grafana:
    build:
      context: grafana
      args:
        UPSTREAM_VERSION: 10.2.0
    image: "grafana.dms.dnp.dappnode.eth:1.0.1"
    restart: always
    volumes:
      - "grafana_data:/var/lib/grafana"
  prometheus:
    build:
      context: prometheus
      args:
        UPSTREAM_VERSION: v2.47.2
    image: "prometheus.dms.dnp.dappnode.eth:1.0.1"
    restart: always
    volumes:
      - "prometheus_data:/prometheus"
      - "prometheus_file_sd:/prometheus_file_sd"
    environment:
      DATA_RETENTION_DAYS: 15
  manager:
    build: ./manager
    image: "manager.dms.dnp.dappnode.eth:1.0.1"
    restart: always
    volumes:
      - "manager_data:/data"
      - "prometheus_file_sd:/prometheus_file_sd"
  loki:
    build:
      context: loki
      args:
        UPSTREAM_VERSION: 2.9.2
    command: "-config.file=/etc/loki/local-config.yaml"
    restart: always
    image: "loki.dms.dnp.dappnode.eth:1.0.1"
  promtail:
    build:
      context: promtail
      args:
        UPSTREAM_VERSION: 2.9.2
    volumes:
      - "/var/log:/var/log:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
    command: "-config.file=/etc/promtail/config.yml"
    restart: always
    image: "promtail.dms.dnp.dappnode.eth:1.0.1"
volumes:
  grafana_data: {}
  prometheus_data: {}
  manager_data: {}
  prometheus_file_sd: {}
