FROM grafana/grafana

# ENV GF_PATHS_DATA=/var/lib/grafana \
#     GF_PATHS_LOGS=/var/log/grafana \
#     GF_PATHS_PLUGINS=/var/lib/grafana/plugins \
#     GF_PATHS_PROVISIONING=/etc/grafana/provisioning
